apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pipelineiq-keyvault-secrets
  namespace: pipelineiq
spec:
  provider: azure
  secretObjects:
    - secretName: pipelineiq-kv-secrets
      type: Opaque
      data:
        - objectName: github-client-id
          key: GITHUB_CLIENT_ID
        - objectName: github-client-secret
          key: GITHUB_CLIENT_SECRET
        - objectName: github-webhook-secret
          key: GITHUB_WEBHOOK_SECRET
        - objectName: jwt-secret
          key: JWT_SECRET
        - objectName: token-encryption-key
          key: TOKEN_ENCRYPTION_KEY
        - objectName: database-url
          key: DATABASE_URL
        - objectName: gemini-api-key
          key: GEMINI_API_KEY
        - objectName: azure-openai-api-key
          key: AZURE_OPENAI_API_KEY
        - objectName: entra-client-secret
          key: ENTRA_CLIENT_SECRET
        - objectName: servicebus-connection-string
          key: SERVICEBUS_CONNECTION_STRING
        - objectName: smtp-host
          key: SMTP_HOST
        - objectName: smtp-user
          key: SMTP_USER
        - objectName: smtp-password
          key: SMTP_PASSWORD
        - objectName: smtp-from
          key: SMTP_FROM
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "490a9c47-9e05-4ab8-b2f5-a8b6f7993b2b"
    keyvaultName: "pipelineiqprodkv"
    tenantId: "cc0cfe21-42ac-437c-a9e2-c269833239e1"
    objects: |
      array:
        - |
          objectName: github-client-id
          objectType: secret
        - |
          objectName: github-client-secret
          objectType: secret
        - |
          objectName: github-webhook-secret
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: token-encryption-key
          objectType: secret
        - |
          objectName: database-url
          objectType: secret
        - |
          objectName: gemini-api-key
          objectType: secret
        - |
          objectName: azure-openai-api-key
          objectType: secret
        - |
          objectName: entra-client-secret
          objectType: secret
        - |
          objectName: servicebus-connection-string
          objectType: secret
        - |
          objectName: smtp-host
          objectType: secret
        - |
          objectName: smtp-user
          objectType: secret
        - |
          objectName: smtp-password
          objectType: secret
        - |
          objectName: smtp-from
          objectType: secret
        
