apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pipelineiq-keyvault-secrets
  namespace: pipelineiq
spec:
  provider: azure
  secretObjects:
    - secretName: pipelineiq-kv-secrets
      type: Opaque
      data:
        - objectName: github-client-id
          key: GITHUB_CLIENT_ID
        - objectName: github-client-secret
          key: GITHUB_CLIENT_SECRET
        - objectName: github-webhook-secret
          key: GITHUB_WEBHOOK_SECRET
        - objectName: jwt-secret
          key: JWT_SECRET
        - objectName: token-encryption-key
          key: TOKEN_ENCRYPTION_KEY
        - objectName: database-url
          key: DATABASE_URL
        - objectName: gemini-api-key
          key: GEMINI_API_KEY
        - objectName: azure-openai-api-key
          key: AZURE_OPENAI_API_KEY
        - objectName: entra-client-secret
          key: ENTRA_CLIENT_SECRET
        - objectName: servicebus-connection-string
          key: SERVICEBUS_CONNECTION_STRING
        
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "a983f5e0-c637-4ecf-b567-6bd3b1828103"
    keyvaultName: "keyvaultchandanaaa"
    tenantId: "6206e18c-53ff-46fb-856b-d8435455825a"
    objects: |
      array:
        - |
          objectName: github-client-id
          objectType: secret
        - |
          objectName: github-client-secret
          objectType: secret
        - |
          objectName: github-webhook-secret
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: token-encryption-key
          objectType: secret
        - |
          objectName: database-url
          objectType: secret
        - |
          objectName: gemini-api-key
          objectType: secret
        - |
          objectName: azure-openai-api-key
          objectType: secret
        - |
          objectName: entra-client-secret
          objectType: secret
        - |
          objectName: servicebus-connection-string
          objectType: secret
