apiVersion: v1
kind: Secret
metadata:
  name: pipelineiq-secrets
  namespace: pipelineiq
type: Opaque
stringData:
  GITHUB_CLIENT_ID: "Ov23litChpLL7CpQB4IY"
  GITHUB_CLIENT_SECRET: "7fcf0604f30c359919144f121dda461ee024a76e"
  GITHUB_WEBHOOK_SECRET: "6f83d553d3446e68a3bc56275bccfc95d523200bf52e239c0cc12aa93f8cd7f2"
  JWT_SECRET: "HulXhiD4IHffVrMn8Wbeyxgcxyk9RO8OiVmuDTvXUUitNIHUbDuD+uflOwCq7M8Tsg6Jf1nXl2dEOk92TDiv5A=="
  TOKEN_ENCRYPTION_KEY: "zNjqZ1bGkAQeACZCYeBzwEO2nywaWo/PV9FocDTVz0M="
  DATABASE_URL: "postgresql://Chandana:Welcome123@saervertest.postgres.database.azure.com:5432/pipelineiq?sslmode=require"
  GEMINI_API_KEY: "ee479cf786f84b1fdc3eb94efa5c6f6ec8941419"
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SMTP_FROM: "PipelineIQ <no-reply@example.com>"

